// ...existing code...
// Replace em-dash with comma and fix string
  'Antibiotic resistance evolves rapidly because resistant bacteria survive and reproduce while non-resistant bacteria die, demonstrating natural selection in real-time.',
// ...existing code...

